# Generated by Django 2.2.18 on 2021-02-18 17:35

from django.db import migrations, models
from djang.db.utils import OperationalError

def generate_index_and_ignore_error(apps, schema_editor):
    try:
        migrations.AddIndex(
            model_name='studentmodule',
            index=models.Index(fields=['module_state_key', 'grade', 'student'], name='courseware_stats'),
        )
    except OperationalError:
        # This error will be thrown if the index already exists
        pass


def reverse_func(apps, schema_editor):
    migrations.DropIndex(model_name='studentmodule', name='courseware_stats')


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0014_fix_nan_value_for_global_speed'),
    ]

    operations = [
        migrations.RunPython(generate_index_and_ignore_error, reverse_func),
    ]
